### PR TITLE
Adding flask app that takes user input and passes into model.

### PR DESCRIPTION
**Pull request by inregards2pluto**

### CODE REVIEW

**Review by CFly17 — APPROVED** [review]

**Comment by PGrickswim** [comment]
Thank you for your hard work on this!

**Review by PGrickswim — APPROVED** [review]
Awesome, thanks!

**Review by lewars1108 — APPROVED** [review]
Good walk-through of the creation of this.

**Review by KiraLivingston — APPROVED** [review]
Great Job Christine, I do not want it to fail! LOL.

**Pull request merged**
